
# Initialize the News API client
import pandas as pd
import numpy as np
import yfinance as yf
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from datetime import datetime, timedelta
from newsapi import NewsApiClient
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch
import logging

newsapi = NewsApiClient(api_key='bf79517bda9f4b01a3dd78b270d19a66')

# Set up logging
logging.basicConfig(filename='trading_analysis.log', level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

def initialize_sentiment_pipeline():
    try:
        logging.info("Initializing sentiment analysis pipeline.")
        model_name = 'distilbert-base-uncased-finetuned-sst-2-english'
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForSequenceClassification.from_pretrained(model_name)
        device = 0 if torch.cuda.is_available() else -1
        sentiment_model = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer, framework='pt', device=device)
        return sentiment_model
    except Exception as e:
        logging.error(f"Error initializing sentiment pipeline: {e}")
        raise

def fetch_and_analyze_news(sentiment_model, date):
    try:
        logging.info(f"Fetching and analyzing news for date: {date}")
        # end_date = date.strftime('%Y-%m-%d')
        startdate=(datetime.now()-timedelta(days=100)).strftime("%Y-%m-%d")
        enddate=datetime.now().strftime("%Y-%m-%d")
        APIKEY = 'bf79517bda9f4b01a3dd78b270d19a66'  # Replace with your NewsAPI key
        news_startdate=(datetime.now()-timedelta(days=30)).strftime("%Y-%m-%d")
    
        newsapi = NewsApiClient(api_key=APIKEY)
        articles = newsapi.get_everything(q='Apple',
                                              language='en',
                                              sort_by='relevancy',
                                              from_param=news_startdate,
                                              to=enddate,
                                              page_size=100,
                                              )
        
        if articles['totalResults'] == 0:
            return 0  # Neutral sentiment if no news

        sentiments = []
        for article in articles['articles']:
            if article['description']:  # Ensure there's a description
                sentiment = sentiment_model(article['description'][:512])[0]
                score = sentiment['score'] if sentiment['label'] == 'POSITIVE' else -sentiment['score']
                sentiments.append(score)

        if sentiments:
            return np.mean(sentiments)
        else:
            return 0
    except Exception as e:
        logging.error(f"Error fetching or analyzing news: {e}")
        raise

def main():
    try:
        logging.info("Starting script execution.")
        
        # Initialize News API client
        logging.info("Initializing News API client.")

        # Initialize sentiment analysis pipeline
        sentiment_model = initialize_sentiment_pipeline()

        # Download historical stock data
        logging.info("Downloading historical stock data.")
        ticker = 'AAPL'
        df = yf.download(ticker, start='2024-07-01', end='2024-07-20')

        # Generate simplified placeholder earnings data
        logging.info("Generating placeholder earnings data.")
        df['earnings'] = np.random.uniform(0.5, 1.5, size=len(df))

        # Apply news sentiment analysis
        logging.info("Applying news sentiment analysis.")
        df['news_score'] = df.index.to_series().apply(lambda date: fetch_and_analyze_news(sentiment_model, date))

        # Feature Engineering
        logging.info("Performing feature engineering.")
        df['price_change'] = df['Close'].pct_change()
        df['volume_change'] = df['Volume'].pct_change()
        df.dropna(inplace=True)  # Drop NaN values generated by pct_change()

        # Model Training
        logging.info("Training Isolation Forest model.")
        features = ['price_change', 'volume_change', 'earnings', 'news_score']
        X = df[features]
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        model = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
        model.fit(X_scaled)

        # Anomaly Detection
        logging.info("Detecting anomalies.")
        df['anomaly'] = model.predict(X_scaled)
        anomalies = df[df['anomaly'] == -1].copy()

        logging.info("Anomalies detected:")
        logging.info(anomalies[['Close', 'anomaly']])

        # Trading Suggestions
        def make_trade_suggestion():
            if len(anomalies) > 0:
                last_anomaly = anomalies.iloc[-1]
                entry_price = last_anomaly['Close']
                exit_price = entry_price * 1.05
                stop_loss_price = entry_price * 0.95

                return {
                    'should_buy': True,
                    'entry_price_range': (entry_price * 0.99, entry_price * 1.01),
                    'exit_price_range': (exit_price * 0.99, exit_price * 1.01),
                    'stop_loss_price': stop_loss_price
                }
            else:
                return {
                    'should_buy': False,
                    'message': 'No anomalies detected.'
                }

        # Get and log trading suggestion
        logging.info("Getting trading suggestion.")
        suggestion = make_trade_suggestion()
        logging.info("Trade Suggestion:")
        for key, value in suggestion.items():
            logging.info(f"{key}: {value}")

    except Exception as e:
        logging.error(f"Error in script execution: {e}")
        print(str(e))

if __name__ == "__main__":
    main()


